services:
  bot:
    image: volgactf-bot
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      target: prod
    command: ["python", "src/bot.py"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: "Europe/Samara"
    volumes:
      - ./config_table.json:/app/config_table.json
    depends_on:
      - redis
      - mongo

  worker:
    command: [ "celery", "-A", "src.worker", "worker", "-l", "INFO", "-B" ]
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      target: prod
    image: volgactf-bot-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: "Europe/Samara"
    volumes:
      - ./config_table.json:/app/config_table.json
    depends_on:
      - bot
      - redis
      - mongo

  mongo:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27019:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  flower:
    image: mher/flower:latest
    command: [ "celery", "-b", "redis://redis:6379", "flower" ]
    restart: unless-stopped
    ports:
      - "5555:5555"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb:
  mongodb_config:
  redis_data:
    external: false
